### ISSUE TITLE
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

### ISSUE THREAD

**Issue by danielkovacsdeak** [HiLab-git/MIDeepSeg#4]
After installing all the packages and running `python main.py`, I got the following error: "OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized. error."

I managed to fix it by installing the `nomkl` package (eg. conda install nomkl). Maybe it should be added to the requirements file if others also have the same issue.

**Comment by Luoxd1996** [comment]
Hi,
Thanks for your suggestion, I will update it later,
Best,
Xiangde.
