### ISSUE TITLE
3D medical image interactive segmentation interface?

### ISSUE THREAD

**Issue by yangshunDragon** [HiLab-git/MIDeepSeg#5]
Hello, thanks for opening source nice work.

For 2D interactive segmentation, you offer the UI for user interaction. What about 3D medical image interactive segmentation?
Is there any UI or App to check as what we see in the demo?
BTW, for 2D and 3D interactive segmentation, are they using the same trained model?

**Comment by Luoxd1996** [comment]
Hi, 
There is not any plan to release the 3D GUI, as the 3D GUI development is very time consuming and expensive so we borrow our collaborators' 3D GUI, we don't have copyright. The 2D and 3D interactive segmentation methods used difference pretrained models, details can be found in our paper.
Best,
Xiangde.

**Comment by yangshunDragon** [comment]
> collaborators' 3D GUI

Hi,  Dear Xiangde 

thanks for quick reply.
For 3D GUI, do you have a suggestion which we could base on for a quick implementation?  

BR,
Shun

**Comment by Luoxd1996** [comment]
Hi, Shun;
MONAILabel is very user-friendly tool, maybe it can help you.
Best,
Xiangde.
