### ISSUE TITLE
cant‘t find the open source of  BIFSeg

### ISSUE THREAD

**Issue by NieXiuping** [HiLab-git/MIDeepSeg#6]
Hi,
Thank you for your time. Recently, I have read the paper of your lab about BIFseg and am very interested in this work. However, I can't open the code link in paper. I am wondering if you can send this work to me or fix the link on your website. 
Looking forward to your reply, Thank you very much!

**Comment by Luoxd1996** [comment]
Hi,
BIFSeg is not open available now, but the core idea is very easy to re-implement by yourself. You can re-implement BIFSeg based on the MIDeepSeg implementation, I think it's easy and interesting.
Best,
Xiangde.

**Comment by NieXiuping** [comment]
Thanks for your reply！I don't understand some parts of the paper. Can I get your contact information for further discussion.

**Comment by Luoxd1996** [comment]
Please send me an email, and I will give you my WeChat ID.

**Comment by nxp1999** [comment]
nxp@zju.edu.cn
